### ISSUE TITLE
Add more padding to bottom of card

### ISSUE THREAD

**Issue by justwheel** [micahdenn/fedora-reddit_theme#1]
One user reported that the padding for buttons (e.g. "Edit", "Reply", etc.) are too close to the bottom in his browser and slightly cut off.

![Padding](https://i.imgur.com/M7SR7Pj.png)

Adding some more spacing to this section might be a good idea for those with browsers or styles that might affect this.

**Comment by micahdenn** [comment]
@jflory7 could you ask him for info on what browser/settings he is using?
I couldn't reproduce this and I don't want to add padding unless its necessary.

**Comment by justwheel** [comment]
@micahdenn My understanding is that all users who reported this were using Chrome, but I'm not sure about specific theming or styling. I'll need to follow up.
