### ISSUE TITLE
Issues with searching the subreddit

### ISSUE THREAD

**Issue by justwheel** [micahdenn/fedora-reddit_theme#2]
Some users reported that they are unable to search the Subreddit with this style's UI.

See the discussion [here](https://www.reddit.com/r/Fedora/comments/433r5t/introducing_our_new_redesign/czqha7k).

Here is the [test case](https://www.reddit.com/r/Fedora/search?q=test&sort=new&restrict_sr=on).

**Comment by ghost** [comment]
#header-img.default-header, #header-img this is the element which overlaps the list, just move it up a tad

**Comment by micahdenn** [comment]
I think this should fix it

`.search-page #header-bottom-left { top: -35px; }`

**Comment by micahdenn** [comment]
@jflory7 did you get a chance to try this yet?

**Comment by justwheel** [comment]
@micahdenn Whoops, missed this. Just applied the change!

@bobpndrgn Let us know if this fixes it for you.
